[package]
name = "libhydrogen"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "A modern and easy to use cryptography library"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-libhydrogen"
repository = "https://github.com/jedisct1/rust-libhydrogen"

[dependencies]
failure = "~0.1"
failure_derive = "~0.1"
libhydrogen-sys = "~0.7"
